branches:
  only:
    - master

stages:
  - test-backend
  - test-frontend

jobs:
  include:
    - stage: test-backend
      language: php
      php:
        - '7.2'
        - '7.3'
        - '7.4'
      install:
        - cp .env.example .env
        - composer install

    - stage: test-frontend
      language: node_js
      node_js:
        - 'lts/*'
