---
version: "3"

services:

  # --- MariaDB 10.4
  db:
    container_name: "linkace-db"
    image: bitnami/mariadb:10.4
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - linkace-db:/bitnami

  # --- PHP 7.4
  php:
    container_name: "linkace-php"
    build:
      context: .
      dockerfile: ./resources/docker/dockerfiles/development.Dockerfile
    depends_on:
      - db
    volumes:
      - .:/app:delegated
      - ./resources/docker/php/php-dev.ini:/opt/bitnami/php/etc/conf.d/php.ini:ro

  # --- nginx 1.14
  nginx:
    container_name: "linkace-nginx"
    image: bitnami/nginx:1.14
    ports:
      - "80:8085"
    depends_on:
      - php
    volumes:
      - .:/app:delegated
      - ./resources/docker/nginx/site.conf:/opt/bitnami/nginx/conf/vhosts/site.conf:ro

  # --- Redis 4.0
  redis:
    container_name: "linkace-redis"
    image: bitnami/redis:5.0
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  linkace-db:
    driver: local
