version: "3"

services:

  # --- MariaDB
  db:
    image: bitnami/mariadb:10.5
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_COLLATE=utf8mb4_bin
    volumes:
      - db:/bitnami

  # --- LinkAce Image with PHP 7.4 and nginx
  app:
    image: linkace/linkace:php-nginx
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "0.0.0.0:80:8080"
      #- "0.0.0.0:443:8443"
    volumes:
      - ./.env:/app/.env
      - ./nginx-simple.conf:/opt/docker/etc/nginx/conf.d/linkace.conf:ro
      - linkace_logs:/app/storage/logs
      # Remove the hash of the following line if you want to use local backups
      #- ./backups:/app/storage/app/backups
      # Remove the hash of the following line if you are using HTTPS
      #- /path/to/your/ssl/certificates:/opt/docker/etc/nginx/ssl

volumes:
  linkace_logs:
  db:
    driver: local
