version: "3"

services:

  # --- MariaDB
  db:
    image: bitnami/mariadb:10.5
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
    volumes:
      - db:/bitnami

  # --- LinkAce Image with PHP 7.4
  app:
    image: linkace/linkace:latest
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - linkace_app:/app
      - ./logs:/app/storage/logs
      - ./.env:/app/.env

  # --- nginx
  nginx:
    image: bitnami/nginx:1.19
    restart: unless-stopped
    ports:
      - "0.0.0.0:80:8080"
      #- "0.0.0.0:443:8443"
    depends_on:
      - php
    volumes:
      - linkace_app:/app
      - ./nginx.conf:/opt/bitnami/nginx/conf/server_blocks/linkace.conf:ro
      #- /path/to/your/ssl/certificates:/certs

  # --- Redis
  redis:
    image: bitnami/redis:6.0
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

volumes:
  linkace_app:
  db:
    driver: local
